---
title: "portfolio-part-1"
format: html
---

## Data Description

**1. Identify your data source.**

These data come from sampling efforts that I participated in over the summer of 2023 for a marine protected area effectiveness evaluation through the Lindholm imagery analysis lab.

**2. Describe your data, including variables and data types.**

Drop_ID - sample (drop) identifier

Date - YYYYMMDD, when the video was taken

Location - the marine protected area that was sampled

Designation - whether the video was taken inside the MPA or outside (REF)

3D Points - number of fish counted in drop

3D Lengths - number of fish measured in drop

Depth (m) - depth of drop in meters

Habitat - Hard = all rock, mixed-hard = mostly rock, mixed-soft = mostly sand/mud, soft = all sand/mud

Relief - High = \>2 meters depth change, Medium = 1-2 meter, Low = \<1 meter

Rugosity - The complexity (holes, cracks, overhangs, etc.) of the habitat

Simpson_div - Gini-Simpson diversity index

Shannon_div - Shannon-Wiener diversity index

**3. Identify the research questions you want to answer.**

How does species diversity vary inside and outside of marine protected areas?

How does relative abundance and size vary inside and out of MPAs?

How does habitat vary inside and out of MPAs?

## Data Visualization

**1. What do you want your final visualizations to look like?**

*How does species diversity vary inside and outside of marine protected areas?*

-   Boxplot of diversity by designation with all locations included, then faceted by location.

*How does relative abundance and size vary inside and out of MPAs?*

-   Bar chart of average abundances by designation

-   Ridgeplot of sizes by designation, with vertical lines showing where the mean or median is.

*How does habitat vary inside and out of MPAs?*

-   Bar plots comparing habitat metrics by designation, faceted by location.

**2. What do you want to highlight on your final visualizations in order to answer your research questions? How do you plan to do that?**

- I want to highlight potential differences, if any, between inside and outside of marine protected areas. I plan on doing that with lines, annotations, and captions.

**3. What is missing from your data or would need to change in your data to create these visualizations?**

- I need to get the average fish sizes by drop, which I will do by summarizing another data set and joining it to the main one I will be using (more details below). 


## Data Cleaning

**1. Do you need to reformat any variables into different types (e.g. factors, time, dates, strings)? Or remove information from variable values?**

Yes, OpCode will need to be reclassified as categorical, not numeric.

**2. Do you need to deal with any missing data, especially missing data coded other than NA?**

There are some missing values for habitat, relief, and rugosity. These are already coded as NA.

**3. Do you need to filter your data? How?**

No

**4. Do you need to create any new variables? What variables? How?**

Yes, I would like to create a species richness variable by grouping by drop then counting the unique species, then joining that table to the drop data. I would also like to create an average fish length variable by grouping by drop then calculating the mean of lengths and joining that to the drop data.

**5. Do you need to add new data (join) to your data? What data? How?**

See above question. The data added comes from the same sampling effort, but looks at individual fish instead of the overall drop.

**6. Are there any variables you can exclude from your data?**

Yes, date and one of the diversity indices can be excluded.

**7. Do you need pivot your data in any way? Why? How?**

No.

**8. Do you need to summarize any of the variables? Which ones? How?**

See question 4.

**9. What other aspects of your data need to be “fixed” in order to make your data visualizations?**

None (hopefully).
